apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-frontend
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    namespaces:
      - onlineboutique
    labelSelectors:
      app: frontend
  stressors:
    cpu:
      workers: 1
      load: 80
  duration: "10m"