apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-cart-repeat
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - onlineboutique
    labelSelectors:
      app: cartservice
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "0ms"
  duration: "2m"