apiVersion: apps/v1
kind: Deployment
metadata:
  name: oversee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oversee
  template:
    metadata:
      labels:
        app: oversee
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: oversee
          image: oversee:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
